### ISSUE TITLE
How to run the goji HTTPS server?

### ISSUE THREAD

**Issue by cliguo** [zenazn/goji#112]
Hi zenazn,
    How to run the goji https server?

    Thank you!

**Comment by 0xdabbad00** [comment]
Instead of `goji.Serve()` you can use `goji.ListenAndServeTLS(certFile, keyFile string)` from https://github.com/zenazn/goji/blob/dcb9598cbbcfcc10d2c1ee1e66958e54a2c84b52/graceful/server.go#L31

But I think you'll probably find it easiest to just use a reverse proxy such as nginx or some other load balancer, for example Amazon AWS's Elastic Load Balancer.

**Comment by elithrar** [comment]
Just to second Scott's suggestion: almost definitely use
nginx/HAProxy/Apache in front for "production", since they have a lot more
tools to handle HTTPS (TLS) deployment. But similarly, there's nothing
wrong with using goji.ListenAndServeTLS to get you started on your dev box
while you work on your app logic first!

PS: https://gist.github.com/elithrar/77ee6746104b900e866c is an excerpt of
the nginx config I use to terminate SSL and then HTTP proxy to my Go
application listening on 127.0.0.0:8001

**Comment by cliguo** [comment]
Thank for your advice.
I already use graceful.ListenAndServeTLS to run goji https server.

**Comment by zenazn** [comment]
Since it looks like you're all set (I'd recommend exactly what @0xdabbad00 and @elithrar said), I'm going to close this issue for now. Please feel free to re-open it if you run into issues with Goji's HTTPS support!
