### ISSUE TITLE
Accessing URL parameters from http.Handlers

### ISSUE THREAD

**Issue by amoghe** [zenazn/goji#113]
When using other routers (such as ```bmizerany/pat```),  URL params (e.g. ```/foo/:bar```) are stored in the request query string URL (req.URL.Query()). This is convenient because we can then write handlers that are ```net/http``` compatible (i.e., they don't take a ```c web.C``` argument) and params are always received from the same location (```req.URL.Query()```)

OTOH, goji prefers to pass these via the ```c.URLParams``` hash. This means handlers have to be written to adhere to the ```web.Handler``` interface, not the ```http.Handler``` interface (accepting the additional ctx object). This makes the code "less portable" especially in a project which might use more than one muxes/routers.

So, my question is - What are the reasons to not pass these params via the ```r.URL.Query()``` ? Is there any scope for a patch that introduces a mode so that goji does this in addition to its default behavior?

**Comment by zenazn** [comment]
The unfortunate part about putting extracting `Path` parameters into the `Query` is that you sacrifice generality. For instance, `pat` can't tell the difference between `/foo?:bar=baz` and `/foo/baz` (for route `/foo/:bar`). (This isn't a perfect example, but you can hopefully see where I'm going with this).

It's possible this just isn't an issue for your use case, and that's fine. But there are cases in which the distinction is important, and all other things being equal I'd like to make Goji as generally applicable as possible. In practice, the reason we have `URLParams` is because I already found myself needing to pass a context object around anyways, so it seemed reasonable to slip `URLParams` in to that struct.

I've been meaning for the longest time to allow for "post-router middleware," and you could implement a backwards compatibility shim for `pat` using that mechanism. I've tried giving people ETAs on that feature, but in practice I haven't been able to hit a single one of these deadlines, so this time I'm not even going to try :P

**Comment by amoghe** [comment]
agreed, 'post-router middleware' is probably the easiest way to provide this compatibility.

Feel free to close this issue (unless you want to track the 'post-router' feature here).

**Comment by zenazn** [comment]
I'm tracking that feature over at #76, so I'm going to close this issue for the time being.
