### ISSUE TITLE
To what extent is Goji thread-safe?

### ISSUE THREAD

**Issue by lthibault** [zenazn/goji#124]
Hello,

I hope this is the appropriate venue for asking such questions, but I'm hoping to write a small web server in which goroutines can be run in parallel. 

Is there any reason why `GOMAXPROCS` cannot be greater than `1`?  Are there any caveats in parallelizing code using Goji?

Thanks for this wonderful framework!

**Comment by elithrar** [comment]
Note that (by default) Go's web server uses a goroutine-per-request —
meaning that requests are served "in parallel" already.

**Comment by lthibault** [comment]
@elithrar Duly noted!  I just wanted to get confirmation that there weren't additional constructs in Goji that were not thread-safe.

Thanks for the info!

**Comment by zenazn** [comment]
There are a few places in the API where non-thread-safe behaviors are called out (most prominently, it is illegal to mutate the middleware stack concurrently with active requests [0]), but beyond that everything is thought to be thread safe (and it's a bug if you find that it isn't). I'm currently running Goji in production at Stripe with `GOMAXPROCS=8`, for instance, and have never seen a Goji-related race.

[0] fun fact: there used to be a bunch of mutation barrier code that allowed you to do this safely, but I ripped it out because it was too complicated and I really didn't want to support that use case

**Comment by lthibault** [comment]
@zenazn Thanks for the info!

Just to be clear, when you say "it's illegal to mutate the middleware stack concurrently with active requests", are you referring to adding/removing middleware components or to something else altogether?

In any case, great library!

**Comment by elithrar** [comment]
Yep, Carl means that changing the middleware stack concurrently (i.e when
processing requests) is Not Good (tm). This is a very rare case though and
there's almost no need to do it. If there was ever a need to decide when to
apply middleware (or not to apply it), then middleware itself should handle
that.

It's a pretty rare case.

**Comment by zenazn** [comment]
I think this is resolved, but feel free to re-open this issue if anything else comes up!
