### ISSUE TITLE
[RFC] middleware for encrypted cookies

### ISSUE THREAD

**Issue by amoghe** [zenazn/goji#125]
Is anyone aware of goji compatible middleware that allows user to set encrypted cookies (possibly using [securecookie](http://www.gorillatoolkit.org/pkg/securecookie))? 

If not, I'd like to create one. One approach would be to set a known key in the `web.C.Env` map (maybe `"Cookies"`) which is itself a `map[string]string` (as described in the securecookie examples). This middleware would assume it gets called early enough so that it can peek into the cookie and populate the map before calling downstream handlers, and eventually serialize (and encrypt) the cookie map into the cookie. Thoughts?

**Comment by elithrar** [comment]
I am working on an auth package with middleware helpers - i.e.
admin.Use(store.RequireAuth) that leverages securecookie and it should be
done Very Soon (tm).

Beyond that - if you're looking for a more general cookie store, I would
leverage gorilla/sessions.

**Comment by amoghe** [comment]
> I am working on an auth package with middleware helpers

Thats cool! Could you point me to the repo (assuming its public) so I could take a look at what kinds of middleware you are planning?

> if you're looking for a more general cookie store, I would leverage gorilla/sessions

Yes, I considered `gorilla/sessions` , but it maintains global state to achieve its goal. In a goji-like framework, we should be able to use `web.C` and completely avoid global state (which is how I started thinking about this).

**Comment by elithrar** [comment]
Repo not public (yet). Hopefully next week though! Just want to lock down
the API before people start go getting it too quickly. The public API is
pretty small though: Provide (makes the store available in the context),
RequireAuth/RequireAdmin (parse for valid values, bounce to an ErrorHandler
on failure), Logout (expires the cookie + token). There are also SetUser
and GetUser functions that facilitate saving and getting a User (an
interface with a couple of simple GetID and IsAdmin methods) as to make it
fairly flexible to plug into an existing app.

Otherwise RE: gorilla/sessions global state - yes, it's a problem*. I
looked at forking gorilla/sessions to strip out `gorilla/context` and use
`web.C` instead, but the public API in sessions relies on the global
context - i.e. there are a couple of public methods that take the request
(only). This means you can't pass in Goji's web.C instead. Breaking the API
means that all of the third party stores (cookies through to Redis through
to mySQL) would no longer work, which is one of the big pluses for using
gorilla/sessions in the first place.

You could probably work with that [forking gorilla/sessions] and rename
your fork (crediting the original authors as per the license) to avoid
confusion, and maybe even port a couple of third party stores over too.
That's not a huge undertaking (technically) but you'll need to re-do the
docs if you want user traction and some parts (the registry) are tightly
coupled with gorilla/context. Or write your own lib, but obviously that's a
slippery slope if you want to have some feature parity with
gorilla/sessions.

Note that this is how I ended up writing my own auth cookie library - the
primary use for sessions is auth, so writing a focused lib was a lot easier
than something as modular as gorilla/sessions.

* Note that the performance impact by the gorilla/context global request
map + mutexes may not be as bad as "global map with mutex" sounds. You
should be able to blow past 12k req/s or more with 400+ concurrent
connections even with the global map.

**Comment by desimone** [comment]
@elithrar Any update?

**Comment by elithrar** [comment]
Almost done! Writing tests. Might be at least a couple of weeks but no
promises—real life work taking precedence right now! ;)
