### ISSUE TITLE
Router allocations

### ISSUE THREAD

**Issue by pkieltyka** [zenazn/goji#132]
Hi, projects like https://github.com/gin-gonic/gin and https://github.com/labstack/echo have demonstrated the possibility of having a zero allocation router, with better performance.. have you thought about improving the goji router to use a similar design?

**Comment by elithrar** [comment]
Note that those routers aren't quite "zero allocation": they both allocate
a pool on init and then re-use that pool. The benchmarks don't account for
that.

**Comment by zenazn** [comment]
Unfortunately the allocations that remain are entirely in generating the maps in `web.C`, which I can't give up due to compatibility guarantees. Even if I could break compatibility I probably wouldn't, though, since they're still (in my opinion at least) a better user interface.

Goji isn't meant to be the fastest router on the block—it's meant to be simple, flexible, and easy to use. While I'll gladly optimize the hell out of the parts I can, I'm not willing to sacrifice these other properties in the name of speed, and I'm not interested in playing the benchmarks game. If your application needs those extra hundred nanoseconds and can't deal with those extra two allocations, then you're probably going to be willing to make different tradeoffs than me, but I suspect exceedingly few people will ever find themselves in that situation.

**Comment by pkieltyka** [comment]
All fair points.

**Comment by zenazn** [comment]
@elithrar Fun fact: Goji actually pools pre-baked middleware stacks (this is called out explicitly in the documentation). 

Which reminds me of another bad user experience foot-gun in these other frameworks: if you save a `gin.Context` or `echo.Context` past the lifetime of the handling request (let's say you're deferring some asynchronous work for later and don't want the response to block on it), you'll find yourself in a use-after-free situation, where the `Context` you're using now belongs to a completely different request than the one you thought you were looking at. This is a class of "memory-safety" bugs we haven't had since dinosaurs roamed the earth and everyone coded in C.

Even though Goji occasionally pools memory, it only does so to middleware authors (and in a documented fashion)—once a route has a `web.C`, every byte of memory in it is theirs forever, to do with however they please.

**Comment by elithrar** [comment]
Great catch: I was unaware of that in Gin/Echo.

I'm also somewhat concerned at the madness of the whole "router benchmarks"
game, given that routing is such a tiny component of the response time. Not
much we can do about that at a large scale though!

**Comment by zenazn** [comment]
Closing this out as a wontfix—I think the semantics Goji provides are the right ones, and it's not worth playing the zero-allocations game.

Although come to think of it it's totally possible to write a zero-allocation middleware for Goji—just memory-pool both maps in `web.C` yourself. But no, I'm not going to accept that patch upstream :)
