### ISSUE TITLE
Support for dynamic method types

### ISSUE THREAD

**Issue by pe-vsn** [zenazn/goji#134]
I may be reading the source wrong, but it doesn't seem possible to have dynamic handlers. For instance, I would like to do something like this:

```
for _, (method, pattern, handler) := range routes.Adhoc {
    goji.HandleUntyped(web.ValidMethodsMap[method], "/" , handler)
}
```

I imagine there is a reason you kept so many useful methods private, but I'm having trouble seeing a way around this. Any suggestions?

**Comment by pe-vsn** [comment]
Or something more syntactically correct...

```
for _, route := range routes.Adhoc {
    goji.HandleUntyped(web.ValidMethodsMap[route.Method], route.Pattern, route.Handler)
}
```

**Comment by zenazn** [comment]
I've kept those methods and variables private because I view them as an implementation detail and not as part of the public API. If you're looking to maintain a data structure with a list of Goji routes this isn't super great, but luckily writing a little adapter isn't so bad (~20 lines or so).

Beyond API cleanliness (which definitely is important to me), the reason I don't want to expose `handleUntyped` is because for performance reasons it doesn't handle non-standard methods very gracefully. I wouldn't want to expose so sharp of an edge in the API.

**Comment by zenazn** [comment]
I'm going to close this issue out as a wontfix—it's very easy (albeit verbose) to stub this out on the client side, and my reasons for keeping Goji's innards hidden still stand. Feel free to re-open the issue or open a new one if you have any other questions though!
