### ISSUE TITLE
How should I know the url is not 404 before execute ServeHTTP on middleware? 

### ISSUE THREAD

**Issue by tomyhero** [zenazn/goji#137]
I am trying to write a own middleware which i do not want to run when 404. 
Is there any good way to do this? Thanks!

```go
func Foo(c *web.C, h http.Handler) http.Handler {

    fn := func(w http.ResponseWriter, r *http.Request) {

      // want to do something like this.
      if notFound == false { 
           // do something. must be before h.ServeHTTP call.
       }

        h.ServeHTTP(w, r)
    }

    return http.HandlerFunc(fn)

}
```

**Comment by zenazn** [comment]
If you insert the router middleware (http://godoc.org/github.com/zenazn/goji/web#Mux.Router) before your middleware, you can look at the resulting Match object (http://godoc.org/github.com/zenazn/goji/web#Match) to determine if there was a matching route.

Note that this isn't quite the same as "will return 404", since the application might decide to return 404 for an unrelated reason.

**Comment by zenazn** [comment]
I'm closing this issue to keep things tidy, but feel free to reopen it or open a new issue if I haven't completely answered your question or if you run into something else!
