### ISSUE TITLE
SubRouters with same basepath

### ISSUE THREAD

**Issue by patbaker82** [zenazn/goji#148]
Is there an goji idiomatic way to the do the following?  I understand I can use inline middleware, but I'm looking to keep things a bit cleaner.

Thanks!

```go
	/*
		UNAUTHORIZED ROUTES
	*/
	api := web.New()
	goji.Handle("/api/v1/*", api)
	api.Use(middleware.SubRouter)

	//-- API Account
	api.Post("/account/signup", accountController.Create)

	//-- API Session
	api.Post("/session", sessionController.Create)

	/*
		AUTHORIZED ROUTES
	*/
	apiAuthorized := web.New()
	goji.Handle("/api/v1/*", apiAuthorized)
	apiAuthorized.Use(middleware.SubRouter)
	apiAuthorized.Use(middleware.ApplyJWTVerify)

	//-- API Session
	apiAuthorized.Delete("/session", sessionController.Destroy)

	// Run Server
	goji.Serve()
```

**Comment by patbaker82** [comment]
I was able to achieve what I wanted, but I feel this will be limiting in the future.  If there is a better way, please let me know!

Thanks

```go
	/*
	   UNAUTHORIZED ROUTES
	*/
	goji.Post("/api/v1/signup", accountController.Create)
	goji.Post("/api/v1/session", sessionController.Create)

	/*
	   AUTHORIZED ROUTES
	*/
	authorized := web.New()
	goji.Handle("/api/v1/*", authorized)

	authorized.Use(middleware.SubRouter)
	authorized.Use(middleware.ApplyJWTVerify)

	//-- API Session
	authorized.Delete("/session", sessionController.Destroy)

	// Run Server
	goji.Serve()
```

**Comment by zenazn** [comment]
Unfortunately, not really—a consequence of routers functioning purely as `http.Handler`s is that it's not easy to exchange information like this. There are a few hacks you can do though, the most interesting of which is something like this (completely untested copypasta):
```
api := web.New()
goji.Handle("/api/v1/*", api)
api.Use(middleware.SubRouter)
api.Post("/account/signup", accountController.Create) // etc
apiAuthorized := web.New()
api.Handle("/*", apiAuthorized)
apiAuthorized.Use(middleware.ApplyJWTVerify)
apiAuthorized.Delete("/session", sessionController.Destroy)
```

This works because you're using the same prefix in both cases: first the uninitialized routes are matched, and if nothing works it falls through to the catchall router which applies the authentication middleware and allows you to match the remainder of your routes.

If you need something fancier, the best I've been able to come up with is to use Goji's router middleware, which allows you to calculate routing information halfway through the middleware stack. Then you can write a middleware that sits after the router which looks at the pattern and handler that were selected (perhaps via a type assertion) to determine if authentication ought to be applied to any given match. I don't have a code sample for this yet, but let me know if you're interested and I can whip something up quickly.

**Comment by elithrar** [comment]
Another option may be to have the `ApplyJWTVerify` middleware accept a
slice of routes that it will skip (i.e. are exempt). Range over your slice
and check the currently matched route—via `web.GetMatch(c)`—against the
routes in the slice.

This might not scale well (in which event use Carl's suggestion above) but
for most cases you just want to exempt your `/login` or `/register` routes
only, which is manageable.

**Comment by patbaker82** [comment]
@zenazn Thanks, thank works and now I understand it :smile: 

@elithrar Good idea, I'll keep that in mind if the need arises.  For now I'm keeping the unauthenticated routes at the base.
