### ISSUE TITLE
store all web.Match objects used to route an endpoint

### ISSUE THREAD

**Issue by bschoch** [zenazn/goji#149]
For metric tracking I need to create a key for each endpoint/method in the app.

I cant use the url on the request object as that sometimes contains an id which would make for different keys for the same endpoint.

I would like to use the patterns on the match object that I can obtain via the goji context.

However if you use subrouting, the prefix to those patterns is lost.

For example.  For the desired key I want "/admin/orders/:id", which I can programmatically assemble from the following two match objects, but at the end of the request in c.Env[web.MatchKey] I only have the second match object.

&{prefix:/admin/ method:1023 pattern:{raw:/admin/* pats:[] breaks:[] literals:[/admin/] wildcard:true} handler:0xc208010d90}
&{prefix:/orders/ method:12 pattern:{raw:/orders/:id pats:[id] breaks:[47] literals:[/orders/ ] wildcard:false} handler:{fn:0x10aa80}}

Since two match objects were used to route the request, it would be nice to have both available at the end of the request when I need to store the metrics.

**Comment by zenazn** [comment]
Oops—this question seems to have fallen through the cracks. Sorry about that!

There's unfortunately no built-in way to do this: you'd have to augment each of your muxes to record the partial pattern that was matched at that point (potentially appending them to some slice you kept in the request context). Finally, when it came time to e.g., record route metrics, you'd concatenate the set of accumulated patterns to derive a "route spec".

Another technique I've seen work well at work is to name each of your "route spec"s. Generally applications only have a few hundred of these, and assigning them each a name like `UpdateCart` or `ListCustomers` isn't too onerous. Then, your metrics can refer to these human-readable names instead of the full route.
