### ISSUE TITLE
Instead of interface for handler why not have 2 signatures?

### ISSUE THREAD

**Issue by jchannon** [zenazn/goji#163]
Hi.

I'm not sure if this is the best place to ask so apologies if its wrong.

I'm new to Golang but have been reading a lot about routers etc and the love/hate gain/tradeoff of all the fwks and routers out there. This is the most elegant router I have found in Go, very Sinatra like and myself coming from a C# background where I'm a core contributor to https://github.com/nancyfx/nancy/  I was looking for something familiar in Go.

I see in the router comments you have `type HandlerType interface{}` which you then type cast at runtime to make sure they match certain signatures.  May I ask why you just didn't double up the signatures in `default.go` so you could pass in a standard res/req signature or a ctx/res/req signature. That way you would get compile time checking?

Thanks

**Comment by elithrar** [comment]
I think the motivation to accept `interface{}` is because you would need methods on `*Mux` to support:

```
- types that implement http.Handler
- types that implement Handler
- func(http.ResponseWriter, *http.Request)
- func(web.C, http.ResponseWriter, *http.Request)
```

There are 11 methods that accept interface, so you would end up with either ~44 methods, or some mix thereof - e.g. don't accept `func(http.ResponseWriter, *http.Request)` explicitly but instead require package users to wrap every function with that signature with `http.HandlerFunc`.

As a Goji user, I think that's a worthwhile trade-off: you get a significantly smaller (and easier to grok/refactor) API. Since Goji also checks your signatures on application start-up (when it compiles your routes) you at least get *some* feedback (that's also easy to test), rather than a rarely-visited route/handler causing a runtime panic an hour or two into a new deployment.

**Comment by jchannon** [comment]
OK thanks for the info :smile:

**Comment by zenazn** [comment]
@elithrar has the principle right but lowballed the numbers a little: Goji supports 9 HTTP methods (CONNECT, DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT, TRACE) and one catch-all (Handle); each of these functions can take arguments of three types in the first position (string, regexp, and Pattern) and four types in the second position (http.Handler, goji.Handler, and the two Func types), for a total of `10*3*4 = 120` variants. And that's not even counting the middleware functions (Use, Insert, Abandon) and the NotFound handler.

I'm in the middle of a Goji 2 / `context.Context` rewrite, and since I've pared the core router's functionality down a bit, it's looking like the next version of Goji will get its type safety with only four variants, which is way more reasonable. I hope to have something that you folks can look at soon!
