### ISSUE TITLE
List of Routes

### ISSUE THREAD

**Issue by donseba** [zenazn/goji#170]
Hi, I was wondering if it is possible to export an list of routes in goji  ? 

I'm looking to automate API documentation, so getting the list from goji directly would save me some work.

**Comment by zenazn** [comment]
Nope, and unfortunately I'm not sure how to do so that wouldn't be better than application-specific abstractions (e.g., a library that wrapped calls to e.g., `goji.Get`).

More broadly, Goji isn't really intended to be used as a source of truth. It was intended to be used as a utility library that is generated from some other source of truth (which for many people is just their initialization code, but can be some database or other internal abstraction)

**Comment by donseba** [comment]
Hello thank you for your reply. 
I've been digging around and found what I need is in the package already. ( atleast I think ) 

It is located here : 
https://github.com/zenazn/goji/blob/master/web/router.go#L46-L50 
```golang
package web 

type route struct {
	prefix  string
	method  method
	pattern Pattern
	handler Handler
}

type router struct {
	lock     sync.Mutex
	routes   []route
	notFound Handler
	machine  *routeMachine
}
```
specifically : 
`routes   []route`

.. It would help me alot if this could be exported. Maybe with an call like : 

`goji.GetRoutes()  []web.route`

Having that I could itirate over the slice and obtain eveything what i need to build the basic API documentation.

**Comment by zenazn** [comment]
I agree that this would be convenient for your use case, however it would significantly complicate Goji's API: I'd have to expose at least two more types and a handful more functions in order to support it.

Instead, I'd view the fact that Goji *also* has a list of your routes as an implementation detail, and suggest you keep your own list in the format you need if you need one.

**Comment by donseba** [comment]
hmm, okay, I guess we have to agree to disagree :) 

IMO if you look at go's design style, it exports anything that is not solely for the package and reusable on other levels. Having to make another layer around goji to register the routes would eventual make another layer of abstraction (read code that needs to be maintained ) . Adding complexity 

Anyway thank you for your response and your work on goji. guess i have to make an wrapper around it.

**Comment by zenazn** [comment]
I don't think that's true—as a concrete example, it's impossible to get a list of routes out of an `net/http.ServeMux`, and I suspect you'd get a very similar response from the Go maintainers if you asked them what you're asking of Goji.

But, like you said, I'm more than happy to agree to disagree on this one (and thanks for bringing the question up in the first place!) :)

**Comment by donseba** [comment]
Hi, 
just for letting you know. I've made an wrapper around the web.Mux structure to do/get what I need. 

You can see it here : https://github.com/donseba/webdoc . I have to refactor some parts but functionaly is stable. 

let me know what you think :)
