### ISSUE TITLE
TLS context is not added to request

### ISSUE THREAD

**Issue by trdyer** [zenazn/goji#202]
I am adding a application feature based on https://tus.io

It requires that the TLS context is added to the request prior to the handler gaining control of the request. The HTTP package provides this context so that calls to `r.TLS()` will return a TLS context if TLS is being used. As a result the library is returning an invalid location (http vs https) as it believes that TLS is not being used on the connection.

Given the godoc on ListenAndServeTLS I assumed that the TLS context behaviour would match the `http` package.

**Comment by zenazn** [comment]
Hrm. This is an odd one!

Are you using `graceful`? If so, that package has a [custom connection type](https://github.com/zenazn/goji/blob/master/graceful/listener/conn.go#L11) to keep track of the state of each HTTP connection. I bet `net/http` only knows how to find the TLS context if the underlying connection object is a [tls.Conn](https://golang.org/pkg/crypto/tls/#Conn).

If you're able to verify the above, depending on how `net/http` is doing the type sniffing we may be able to make a small change to `graceful` to add support for `r.TLS()`. If not, you might need to find a new solution to graceful shutdown (Go's built-in functionality here has improved greatly since I wrote this package!)

**Comment by trdyer** [comment]
Hey, sorry for taking so long to get back to you. Yes, I was using graceful. It does seem like the custom connection type was at play, I ended up just switching to the native golang option. thanks.
