### ISSUE TITLE
How can I log real-ip using the middleware and goji.serve ?

### ISSUE THREAD

**Issue by depado** [zenazn/goji#89]
Hi,
I'm currently using goji, and it's running behind an nginx reverse proxy. I set the headers passed to the application and used the middleware defined in `goji/web/middleware`  
Now goji.Serve() prints the connections to stdout which are written to a file using supervisor. In the stdout, despite using the RealIP middleware, it still prints that the connections are made from my localhost (which actually is the case, but not the intended behaviour).    

Is there a way I could use the standard output but with the RealIP ?

**Comment by jeremejevs** [comment]
Not that this is a big issue, but what's the reason for not having `middleware.RealIP` in the default muxer? It's a pretty low-cost middleware, and it's needed in most production environments anyway (the place where performance actually matters), since they're [very?] likely to be behind a reverse proxy.

**Comment by elithrar** [comment]
If you have it on by default in a non-proxied environment there's the (very
real) risk that the IP you expect to be "real" may be forged. This is a
sharp edge for users who don't know better.

nginx/HAProxy/Apache overwrite this header in full when you're proxying
upstream, which helps avoid this (or at least you may be more aware).

Since it's set-and-forget it's probably the better trade-off to explicitly
require the middleware to be added.

**Comment by jeremejevs** [comment]
Alright, makes sense, thanks.
